# Generated by Django 6.1.1 on 2026-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='reports/images/')),
                ('documento', models.FileField(upload_to='reports/docs/')),
                ('audio', models.FileField(upload_to='reports/audios/')),
                ('video', models.FileField(upload_to='reports/videos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
