# Generated by Django 6.1.1 on 2026-09-23 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deportivos_guadalupe', '0003_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen_archivo',
            field=models.ImageField(blank=True, upload_to='vehicles/images/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo_3d_archivo',
            field=models.FileField(blank=True, upload_to='vehicles/models/'),
        ),
    ]
