# Generated by Django 6.1.1 on 2026-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deportivos_guadalupe', '0004_alter_vehiculo_options_vehiculo_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-fecha_publicacion', '-id']},
        ),
    ]
