# Generated by Django 6.1.1 on 2026-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deportivos_guadalupe', '0005_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='modelo_3d_embed_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo_3d_url',
            field=models.TextField(blank=True),
        ),
    ]
