name: Suma de Números

on:
  push:
    branches:
      - main
      - master
      - workflow/suma

jobs:
  suma:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v5
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Ejecutar script de suma
        run: python suma.py